apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config # Имя вашего ConfigMap
  namespace: monitoring # Пространство имен, где будет развернут Loki
data:
  config.yaml: | # Ваша конфигурация Loki будет здесь, под ключом config.yaml
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    common:
      path_prefix: /loki
      replication_factor: 1
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory

    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/cache
      filesystem:
        directory: /loki/chunks

    schema_config:
      configs:
        - from: 2020-10-27
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    query_range:
      max_retries: 5
      align_queries_with_step: true

    limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: 168h # 7 дней
      max_streams_per_user: 0 # 0 = без лимита
      max_chunks_per_query: 2000000
      max_query_series: 5000000
      max_query_lookback: 720h # 30 дней.
      allow_structured_metadata: false

#    otlp:
#      grpc_listen_port: 4317
#      http_listen_port: 4318