apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minipc-selfsigned
spec:
  secretName: minipc-selfsigned-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: archonmac.local
  dnsNames:
    - archonmac.local
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}