---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring # Должно совпадать с namespace Grafana
spec:
  accessModes:
    - ReadWriteOnce # Это означает, что том может быть подключен в режиме чтения/записи одним подом
  resources:
    requests:
      storage: 1Gi # Запросите 1 Гигабайт места. Можете изменить по необходимости.
  # storageClassName: standard # Опционально: если у вас нет StorageClass по умолчанию, или вы хотите использовать конкретный