---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
        metrics_path: '/prometheus/metrics' # Исправленный путь для самомониторинга Prometheus

      - job_name: 'kubelet-cadvisor'
        scheme: https
        metrics_path: /api/v1/nodes/${__param_node}/proxy/metrics/cadvisor
    #    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    #    tls_config:
    #      insecure_skip_verify: true
    #    kubernetes_sd_configs:
    #      - role: node
    #    relabel_configs:
    #      - source_labels: [__meta_kubernetes_node_name]
    #        target_label: __param_node
    #      - source_labels: [__param_node]
    #        target_label: node
    #      - target_label: __address__
    #        replacement: kubernetes.default.svc:443


      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          #- source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          #  action: keep
          #  regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          # ИСПРАВЛЕНИЕ: Правильный regex для обработки порта из аннотации
          # Захватываем IP ([^:]+), опционально игнорируем существующий порт (?::\d+)?,
          # затем захватываем порт из аннотации (\d+) после точки с запятой.
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            target_label: __address__
            replacement: $1:$2
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name

      - job_name: 'node-exporter-host'
        static_configs:
           - targets: ['host.k3d.internal:9100']