apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-sa # Имя вашего ServiceAccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-cluster-role # Имя ClusterRole
rules:
  - apiGroups: [""] # Указывает на основные ресурсы Kubernetes (pods, services, nodes)
    resources: ["nodes", "nodes/proxy", "services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions", "apps"] # Для получения информации о Deployments, DaemonSets и т.д.
    resources: ["daemonsets", "replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"] # Может понадобиться, если Prometheus читает ConfigMaps
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-cluster-role-binding # Имя привязки
subjects:
  - kind: ServiceAccount
    name: prometheus-sa # Имя ServiceAccount, созданного выше
    namespace: monitoring # Namespace, в котором находится ServiceAccount
roleRef:
  kind: ClusterRole
  name: prometheus-cluster-role # Имя ClusterRole, созданного выше
  apiGroup: rbac.authorization.k8s.io