apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:0.128.0
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
    processors:
      batch:
        timeout: 5s
        send_batch_size: 1024
      transform/fix_body:
        log_statements:
          - context: log
            statements:
              - set(body, String(body)) where not IsString(body)
      transform/loki_labels:
        log_statements:
          - context: resource
            statements:
              - set(attributes["k8s.namespace.name"], resource.attributes["k8s.namespace.name"])
              - set(attributes["k8s.pod.name"], resource.attributes["k8s.pod.name"])
              - set(attributes["k8s.container.name"], resource.attributes["k8s.container.name"])
              - set(attributes["service.name"], resource.attributes["service.name"])
          - context: log
            statements:
              - set(attributes["job"], attributes["service.name"])

    exporters:
      debug:
      prometheus:
        endpoint: "0.0.0.0:8889"
      loki:
        endpoint: http://loki-service.monitoring.svc.cluster.local:3100/loki/api/v1/push
        tls:
          insecure: true
        default_labels_enabled:
          service.name: true
          job: true
          k8s.namespace.name: true
          k8s.pod.name: true
          k8s.container.name: true
      file:
        path: /host/otel-logs/otelcol.log
        format: json
    #      debug:
    #        verbosity: detailed

    service:
      telemetry:
        logs:
          level: error
      #          level: debug
      pipelines:
        logs:
          receivers: [otlp]
          processors: [transform/fix_body, transform/loki_labels, batch]
          #          exporters: [loki,file]
          exporters: [loki]
        traces:
          receivers: [ otlp ]
          exporters: [ debug ]
        metrics:
          receivers: [ otlp ]
          exporters: [ debug,prometheus ]
  #          exporters: [loki, debug]
  volumeMounts:
    - name: host-logs
      mountPath: /host/otel-logs
  volumes:
    - name: host-logs
      hostPath:
        path: /var/log/otel-logs
        type: DirectoryOrCreate
