apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- ../../../iac/environments/dev1 # Переконайтеся, що цей шлях коректний для вашого середовища
patchesStrategicMerge:
    - patch-kustomization-decryption.yaml
    - patch-kustomize-env.yaml
