apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kbot
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm
      sourceRef:
        kind: GitRepository
        name: kbot-src
  install:
    createNamespace: true
  upgrade:
    cleanupOnFail: true
  values:
    replicaCount: 1